[book]
authors = ["Denis Gorbachev"]
language = "en"
multilingual = true
src = "src"
title = "Zenbox"

[build]
create-missing = false

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false # defaults to false, change to true to create SVG files instead of rendering them inline
